apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: components
  namespace: flux-system
spec:
  chart:
    spec:
      chart: .
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cluster-components-flux-helm
  interval: 10m0s
  values:
    departmentCode: 2
    alpha:
      values:
        replicaCount: 2
    bravo:
      values:
        replicaCount: 2
    charlie:
      enabled: true
