apiVersion: v1
kind: ConfigMap
metadata:
  name: components-values-config
  namespace: flux-system
data:
  values: |
    alpha:
      values:
        replicaCount: 2
        version: "6.6.1"
        resources:
          requests:
            cpu: "1m"
            memory: "21Mi"    
    bravo:
      values:
        replicaCount: 1
    charlie:
      version: 6.6.0
    keda:
      values:
        resources:
          operator:
            limits:
              cpu: 75m
        operator:
          replicaCount: 3
