apiVersion: v1
kind: ConfigMap
metadata:
  name: keda-values-config
  namespace: flux-system
data:
  keda: |
    keda:
      values:
        resources:
          operator:
            limits:
              cpu: 75m
        operator:
          replicaCount: 3
