---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-components-flux-helm
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
    # tag: v0.1.0
  url: https://github.com/merusso/cluster-components-flux-helm.git
---
!include shared.yaml
