version: '3'

tasks:
  apply: kubectl apply -f flux-system
  delete: kubectl delete -f flux-system
  
  reconcile:
    desc: Manually trigger Flux reconciliation
    cmds:
      - flux reconcile kustomization flux-system --with-source
      - flux reconcile source git cluster-components-flux
      - flux reconcile kustomization components --with-source

  wait:
    desc: Wait for deployment to complete
    cmds:
      - kubectl wait -n flux-system kustomization components --for=condition=Ready --timeout=5m
      - kubectl wait -A helmrelease -l atmos.guidewire.com/cluster-component=true --for=condition=Ready --timeout=5m